kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang
  commands:
    -   go build   -o dnsname plugins/meta/dnsname
  
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: gh_token
    note: dsnamed
    overwrite: true  
    files: dnsname
