kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang
  commands:
    - GOARCH=386 go build -o bin/dnsname github.com/containers/dnsname/plugins/meta/dnsname
  
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: gh_token
    note: dsnamed
    overwrite: true  
    files: bin/dnsname
  when:
    event: tag
