kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang
  commands:
    - GO_BUILD=GO111MODULE=on $(GO) build -mod=vendor
  
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: gh_token
    note: dsnamed
    overwrite: true  
    files: dnsname
